faiss_db:
  collection_name: "document_portal"


embedding_model:
  provider: "sentence-transformers"
  embedding_model_name: "sentence-transformers/all-MiniLM-L6-v2"

retriever:
  top_k: 10

llm:
  groq:
    provider: "groq"
    model_name: "openai/gpt-oss-120b"
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0
    max_output_tokens: 2048